### ISSUE TITLE
[WIP] RFC: Dependency management

### ISSUE THREAD

**Issue by slint** [inveniosoftware/rfcs#29]
[CodiMD for the RFC](https://codimd.web.cern.ch/lFwbR-zWRHiB6SnDF1imZg?both)

## Summary

- Bundling of 3rd-party dependencies in "coordinator" packages
- For Travis CI builds pass only the module's "pure" extras to
  `requirements-builder` (i.e. not `all`/`tests`/`docs`)
- Introduce tilde constraints (`~=`) to all modules.

## Motivation

Dependency management is hard and unfortunately an unsolved problem for the
Python packaging ecosystem, and as an extension of that, also for the Invenio
ecosystem. Common issues that developers come across:

- 3rd-party dependencies release versions with breaking changes, that require
  us to have to quickly respond by either:
  - Writing compatibility fixes
  - Accepting the breaking changes and releasing a new backwards-incompatible
    version of the Invenio module
  - Upper-pin versions of the problematic 3rd-party modules
- 3rd-party dependency declarations are scattered around the different modules.
  This causes the following problems:
  - It's difficult to know where a library is being installed from
  - When deciding to bump the minimum version (or upper-pin) a 3rd-party
    library, many changes have to be made across all Invenio modules.
- When running a module's tests we should always be using the latest versions
  of test dependencies, i.e. there's no reason to run tests with minimum
  requirements in Travis CI.

## Template for logging dependency management issues examples

Please copy/paste this template, and add it as a comment to this ticket if you have found an example of dependency management issues in Invenio:

```
- Invenio module and version: 
- Third-party library and version:
- Short description of what happened:
- Link to Travis CI build if available:
```

**Comment by frankois** [comment]
### Classification outcome

Results of the following script: https://gist.github.com/frankois/83856a2aaebe44ed80c7bb319e578f0c

| Packages | Current | PIP2020 | Python package |
| --- | --- | --- | --- |
| invenio-access | :white_check_mark: | :white_check_mark: | |
| invenio-accessrequests | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-accounts | :white_check_mark: | :white_check_mark: | |
| invenio-accounts-rest | :white_check_mark: | :white_check_mark: | |
| invenio-admin | :white_check_mark: | :white_check_mark: | |
| invenio-app | :white_check_mark: | :white_check_mark: | |
| invenio-app-ils | :white_check_mark: | :white_check_mark: | |
| invenio-app-rdm | :x: | :white_check_mark: | |
| invenio-archivematica | :x: |  | |
| invenio-assets | :white_check_mark: | :white_check_mark: | |
| invenio-base | :white_check_mark: | :white_check_mark: | |
| invenio-cache | :white_check_mark: | :white_check_mark: | |
| invenio-celery | :white_check_mark: | :white_check_mark: | |
| invenio-charts-js | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-circulation | :white_check_mark: | :white_check_mark: | |
| invenio-cli | :white_check_mark: | :white_check_mark: | |
| invenio-collections | :white_check_mark: | :white_check_mark: | |
| invenio-communities | :white_check_mark: | :white_check_mark: | |
| invenio-config | :white_check_mark: | :white_check_mark: | |
| invenio-csl-js | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-csl-rest | :white_check_mark: | :white_check_mark: | |
| invenio-db | :white_check_mark: | :white_check_mark: | |
| invenio-deposit | :x: | :white_check_mark: | |
| invenio-drafts-resources | :white_check_mark: | :white_check_mark: | |
| invenio-exporter | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-files-js | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-files-processor | :white_check_mark: | :white_check_mark: | |
| invenio-files-rest | :white_check_mark: | :white_check_mark: | |
| invenio-formatter | :white_check_mark: | :white_check_mark: | |
| invenio-github | :x: | :white_check_mark: | |
| invenio-i18n | :white_check_mark: | :white_check_mark: | |
| invenio-iiif | :white_check_mark: | :white_check_mark: | |
| invenio-index-migrator | :white_check_mark: | :white_check_mark: | |
| invenio-indexer | :white_check_mark: | :white_check_mark: | |
| invenio-jsonschemas | :white_check_mark: | :white_check_mark: | |
| invenio-logging | :white_check_mark: | :white_check_mark: | |
| invenio-mail | :white_check_mark: | :white_check_mark: | |
| invenio-marc21 | :white_check_mark: | :white_check_mark: | |
| invenio-migrator | :white_check_mark: | :white_check_mark: | |
| invenio-oaiharvester | :white_check_mark: | :white_check_mark: | |
| invenio-oaiserver | :white_check_mark: | :white_check_mark: | |
| invenio-oauth2server | :white_check_mark: | :white_check_mark: | |
| invenio-oauthclient | :white_check_mark: | :white_check_mark: | |
| invenio-openaire | :white_check_mark: | :white_check_mark: | |
| invenio-opendefinition | :white_check_mark: | :white_check_mark: | |
| invenio-orcid | :white_check_mark: | :white_check_mark: | |
| invenio-pages | :white_check_mark: | :white_check_mark: | |
| invenio-pidrelations | :white_check_mark: | :white_check_mark: | |
| invenio-pidstore | :white_check_mark: | :white_check_mark: | |
| invenio-previewer | :white_check_mark: | :white_check_mark: | |
| invenio-previewer-ispy | :white_check_mark: | :white_check_mark: | |
| invenio-query-parser | :white_check_mark: | :white_check_mark: | |
| invenio-queues | :white_check_mark: | :white_check_mark: | |
| invenio-rdm-records | :white_check_mark: | :white_check_mark: | |
| invenio-records | :white_check_mark: | :white_check_mark: | |
| invenio-records-editor | :white_check_mark: | :white_check_mark: | |
| invenio-records-editor-js | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-records-files | :white_check_mark: | :white_check_mark: | |
| invenio-records-js | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-records-permissions | :white_check_mark: | :white_check_mark: | |
| invenio-records-resources | :white_check_mark: | :white_check_mark: | |
| invenio-records-rest | :white_check_mark: | :white_check_mark: | |
| invenio-records-ui | :white_check_mark: | :white_check_mark: | |
| invenio-rest | :white_check_mark: | :white_check_mark: | |
| invenio-s3 | :white_check_mark: | :white_check_mark: | |
| invenio-saml | :x: | :x: | |
| invenio-search | :white_check_mark: | :white_check_mark: | |
| invenio-search-js | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-search-ui | :white_check_mark: | :white_check_mark: | |
| invenio-sequencegenerator | :white_check_mark: | :white_check_mark: | |
| invenio-sipstore | :white_check_mark: | :white_check_mark: | |
| invenio-sitemap | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-software.org | :heavy_minus_sign: | :heavy_minus_sign: | :x: |
| invenio-sse | :white_check_mark: | :white_check_mark: | |
| invenio-stats | :white_check_mark: | :white_check_mark: | |
| invenio-theme | :white_check_mark: | :white_check_mark: | |
| invenio-userprofiles | :white_check_mark: | :white_check_mark: | |
| invenio-webhooks | :white_check_mark: | :white_check_mark: | |
| invenio-xrootd | :x: | :x: | |

**Comment by frankois** [comment]
Linked issues:
- https://github.com/inveniosoftware/invenio-saml/issues/12
- https://github.com/inveniosoftware/invenio-xrootd/issues/25

**Comment by lnielsen** [comment]
- Invenio module and version: Invenio-Previewer
- Third-party library and version: nbconvert
- Short description of what happened: https://github.com/inveniosoftware/invenio-previewer/pull/127

Caused InvenioRDM and others not to be installable.

**Comment by fenekku** [comment]
- Invenio module and version: Invenio-Celery
- Third-party library and version: celery
- Short description of what happened: celery 5.0 was released, bringing breaking changes to invenio-celery (e.g. `celery_config` fixture not found)

**Comment by fenekku** [comment]
(slightly different than above but definitely related to this issue)
- Short description of what happened: 

- InvenioRDM ships a Pipfile (but not Pipfile.lock) to pin the invenio-app-rdm version for the month's release. 
- invenio libraries don't necessarily have an upper version bound (e.g. invenio-records-resources has `"invenio-pidstore>=1.2.0",` but this also goes for 3rd party)
- New package versions are released during the month (by us or third-party)

Combined these create unstable installs for InvenioRDM, depending on when the prospective developers install their instance. Potential solutions we are trying: 
-
 upper-bounding our rdm libraries since they see a lot of change during a month and we don't want the current month's development with the previous month's release
- pinning in the Pipfile these libraries that see a lot breaking change (double insurance)

**Comment by lnielsen** [comment]
### Examples:

Using requirements-builder with the new PIP resolver causes dependency issues for lowest releases.

```
# ... Invenio module 
install_requires = [
  'click>=6.0.0',
  'a-third-party-lib>=1.0.0',
]

# ... a-third-party-lib 
install_requires = [
  'click>=6.6.0',
]
```

Requirements builder for lowest requirements will generate the requirements

```
click==6.0.0
a-third-party-lib==1.0.0
```

This will cause pip trying to install click 6.0.0 but find that it is incompatible with the click > 6.6 requirement

**Comment by lnielsen** [comment]
Here's a read of why not to pin dependencies in libraries: https://iscinumpy.dev/post/bound-version-constraints/
