### ISSUE TITLE
[Proposal] Request details page - technical implementation

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/rfcs#58]
https://codimd.web.cern.ch/q3f6wZYSR1-SvJxrwCrkPw?both

**Comment by ntarocco** [comment]
I reviewed the CodiMD and changed a few things. LGTM, good work! 👏🏼 
Can you please read it again, make/suggest changes and create the pull request?

**Comment by jbenito3** [comment]
LGTM, excellent work!
