### ISSUE TITLE
[Proposal] UUIDs as persistent ids

### ISSUE THREAD

**Issue by orviz** [inveniosoftware/rfcs#75]
### Motivation

Some metadata catalogs are using UUIDs as identifiers for the metadata records (e.g. [EPOS data portal](https://www.ics-c.epos-eu.org/)). Agreeing on whether this approach is persistent will help to evaluate compliance with FAIR principles.

[RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html) support this fact (see "Motivation").

### Summary

Consider UUIDs (Universally Unique Identifier) as persistent identifiers, in particular being supported through [idutils](https://github.com/inveniosoftware/idutils)

### Resources

> Which resources do you have available to implement this RFC and what is your overall timeline?

If approved, this change will be implemented with resources coming from an European Commission's research project.

> Note: Creating a new RFC is a moderated process. Your request will be reviewed by the Invenio Architects on their weekly meeting. This is to aid scoping the RFC and avoid duplication of RFCs. If accepted, an architect is assigned to your RFC as your point-of-contact, and the architect will support you in writing the RFC.

**Comment by lnielsen** [comment]
Thanks for the proposal. IDUtils implement support for **persistent** unique identifiers that you cannot already validate via existing Python code. Python already have extensive support for validating UUIDs so we don't see the need to include it in IDUtils, and also UUIDs by themselves are not persistent - it needs a resolver as well. Several of the support PIDs do use UUIDs as part of the infrastructure, but not by itself. Internally in InvenioRDM, we use UUIDs extensively.
