### ISSUE TITLE
[Proposal] <Your RFC title><eden790><

### ISSUE THREAD

**Issue by Eden790** [inveniosoftware/rfcs#77]
### Motivation

> Why are we doing this? What user stories does it support? What is the expected outcome?

### Summary

> What are you proposing to change (high-level overview only)?

### Resources

> Which resources do you have available to implement this RFC and what is your overall timeline?

> Note: Creating a new RFC is a moderated process. Your request will be reviewed by the Invenio Architects on their weekly meeting. This is to aid scoping the RFC and avoid duplication of RFCs. If accepted, an architect is assigned to your RFC as your point-of-contact, and the architect will support you in writing the RFC.
<<Eden790><

**Comment by slint** [comment]
Closing after looking at the creator's GitHub activity history
